id: P3BF6B6C5
initial_creation_type: ocr
source_metadata:
  volumes:
    5f940a27f4ea412c9e15088e608efb33:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: རྡོ་རྗེ་བདེ་རྒྱས་དབྱངས་ཅན་མའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
