id: D2B00D48F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:37:59+00:00'
last_modified: '2022-05-26T10:45:14.195490+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    5eb9:
      image_group_id: I1PD95869
      title: རྡོ་རྗེ་བདེ་རྒྱས་དབྱངས་ཅན་མའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      order: 24
      base_file: 5eb9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
